#!/bin/env/bash
accelerate  launch  \
    --mixed_precision  bf16  \
    --num_cpu_threads_per_process  1  \
    --num_processes  1   # run on 1 gpu remove this line for multi-gpu trainin  \
    tr(root_dir / sd-scripts / "flux_train_network.py"  \
    --dataset_config  config['dataset_config']  \
    --pretrained_model_name_or_path  config['MODEL_PATH']  \
    --clip_l  config['CLIP_L_PATH']  \
    --t5xxl  config['T5XXL_PATH]'  \
    --ae  config['AE_PATH']  \
    --save_model_as  safetensors  \
    --sdpa  \
    ## (['--alpha_mask'] if config['alpha_mask'] else []  \
    --persistent_data_loader_workers  \
    --max_data_loader_n_workers  2  \
    --seed  config['seed']  \
    --gradient_checkpointing  \
    --mixed_precision  bf16  \
    --save_precision  bf16  \
    --fp8_base  \
    --gradient_accumulation_steps  config[gradient_accumulation_steps  \
    --network_train_unet_only  \
    --network_module  networks.lora_flux  \
    --network_dim  config['lora_rank'  \
    --optimizer_type  adamw8bit  \
    --optimizer_args  weight_decay=0.1  \
    --learning_rate  config['learning_rate']  \
    --noise_offset  config['noise_offset']  \
    --noise_offset_random_strength  \
    --ip_noise_gamma  config['ip_noise_gamma']  \
    --ip_noise_gamma_random_strength  \
    --lr_scheduler  cosine_with_restarts  \
    --lr_scheduler_num_cycles  3  \
    --network_alpha  config[lora_rank  \
    --min_snr_gamma  5  \
    --cache_latents_to_disk  \
    --cache_text_encoder_outputs_to_disk  \
    --max_grad_norm  0.0  \
    --text_encoder_batch_size  4  \
    --highvram  \
    --max_train_steps  config['max_train_steps']  \
    --save_every_n_steps  config['save_every_n_steps']  \
    --sample_every_n_steps  config['sample_every_n_steps']  \
    --sample_prompts  config['eval_prompts']  \
    (['--sample_at_first'] if config['sample_at_first'] else []  \
    --output_dir  str(config[output_dir])  \
    --output_name  config[output_name]  \
    --timestep_sampling  shift  \
    --discrete_flow_shift  3.1582  \
    --model_prediction_type  raw  \
    --guidance_scale  config[guidance_scale]
