[general]
flip_aug = true
color_aug = false
shuffle_caption = false
caption_tag_dropout_rate = 0.0
caption_extension = ".txt"


[[datasets]]
batch_size = 1
enable_bucket = true
resolution = 512
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

  [[datasets.subsets]]
  image_dir = "datasets/main"
  num_repeats = 1
